### ISSUE TITLE
Home page doesn't always reflect upcoming events 

### ISSUE THREAD

**Issue by ndesimone** [Dan-in-CA/SIP#198]
Maybe I'm missing something really obvious.
- I created program 3 (all others disabled) with a schedule to only water the lawn for Saturday (today) and a few days next week.  Initially, the program was set to run at 7:15
- I moved the time to 14:30

![pastedgraphic-2](https://user-images.githubusercontent.com/1914205/35184676-ad3eae58-fdad-11e7-8307-86e64c0bbb70.png)

![pastedgraphic-4](https://user-images.githubusercontent.com/1914205/35184681-b3232e48-fdad-11e7-9b97-eaf1ac04ad39.png)

- The homepage doesn't reflect the change

![pastedgraphic-3](https://user-images.githubusercontent.com/1914205/35184682-b65964c4-fdad-11e7-984e-62ee3a7cfaa4.png)

What am I missing?

**Comment by Dan-in-CA** [comment]
Hi Nick,

I have tried duplicating your programs on my test rig and see the same problem.

It looks like it results from changing the start time when "single pass" has been set. As I recall the single pass setting is implemented by a sort of hack. It sets the stop time to be the same as the start time plus the duration to avoid multiple passes. I am not sure why it does not accept a change an I will look into the cause. It also looks like changing the setting to recurring is not saved.

I am currently working on a modification of SIPs irrigation program data format. This will involve changing how "single pass" works. I will make sure this problem is fixed.

Thanks for the bug report, I will post here when I have it fixed.

Dan

**Comment by pansegrau** [comment]
Try scrolling to the following Monday.  I suspect you will not see the change until then.  I also noticed that it does not immediately update to the current day or hour.

**Comment by Dan-in-CA** [comment]
I believe this has been resolved.
